version: '3.5'

services:

  mongo:
    env_file: .env
    container_name: mongo
    image: mongo
    command: mongod --port 27017
    environment:
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    volumes:
      - mongo_db:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - botnet

  db:
    container_name: postgres
    image: postgres:13.3
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - "5435:5432"
    networks:
        - botnet

  bot:
    container_name: bot-template
    build:
      dockerfile: docker_test.dockerfile
      context: .
    env_file:
      - ./app/.env
    volumes:
      - .:/src
    environment:
      - MONGODB_HOSTNAME=mongo
      - POSTGRES_HOST=db
    networks:
      - botnet
    depends_on:
      - mongo

volumes:
  mongo_db:
  postgres_db:

networks:
  botnet:
    driver: bridge