version: '3.5'

services:

  mongo:
    env_file: .env
    container_name: mongo
    image: mongo
    command: mongod --port 27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - mongo_db:/data/db
    ports:
      - '27017:27017'
    networks:
      - botnet

#  bot:
#    container_name: bot-template
#    build:
#      context: .
#    restart: always
#    env_file:
#      - .env
#    volumes:
#      - .:/src
#    environment:
#      MONGODB_HOSTNAME: $MONGODB_HOSTNAME
#    networks:
#      - botnet
#    depends_on:
#      - mongo

volumes:
  mongo_db:

networks:
  botnet:
    driver: bridge