"""empty message

Revision ID: 02803c68951a
Revises: 
Create Date: 2022-05-05 20:21:03.503037

"""
from alembic import op
import sqlalchemy as sa

import app.models.sql.types
from app.models.sql.enums import PaymentType, TripStatus, JuridicalStatus, ServiceType

# revision identifiers, used by Alembic.
revision = '02803c68951a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('lon', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    op.create_table('trip',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('commentary', sa.String(), nullable=True),
    sa.Column('departure_date', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('caption_path', sa.String(), nullable=True),
    sa.Column('juridical_status', app.models.sql.types.IntEnum(JuridicalStatus), nullable=False),
    sa.Column('trip_status', app.models.sql.types.IntEnum(TripStatus), nullable=False),
    sa.Column('payment_type', app.models.sql.types.IntEnum(PaymentType), nullable=False),
    sa.Column('services', sa.ARRAY(app.models.sql.types.IntEnum(ServiceType)), nullable=False),
    sa.Column('departure_location_id', sa.Integer(), nullable=True),
    sa.Column('arrival_location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['arrival_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['departure_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caption_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('location')
    # ### end Alembic commands ###
