"""empty message

Revision ID: 68b6287bfcd3
Revises: c417279873a5
Create Date: 2022-05-23 11:46:09.052927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b6287bfcd3'
down_revision = 'c417279873a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'address_1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trip', 'address_2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trip', 'address_3_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'address_3_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trip', 'address_2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trip', 'address_1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
