"""empty message

Revision ID: b0b14ae5ddc4
Revises: 
Create Date: 2022-06-04 19:36:48.543147

"""
from alembic import op
import sqlalchemy as sa

from app.models.sql.enums import JuridicalStatus, TripStatus, PaymentType, ServiceType
from app.models.sql.types import IntEnum

# revision identifiers, used by Alembic.
revision = 'b0b14ae5ddc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('lat', sa.String(), nullable=False),
    sa.Column('lon', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    op.create_table('trip',
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('commentary', sa.String(), nullable=True),
    sa.Column('departure_date', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('caption_path', sa.String(), nullable=True),
    sa.Column('juridical_status', IntEnum(JuridicalStatus), nullable=False),
    sa.Column('trip_status', IntEnum(TripStatus), nullable=False),
    sa.Column('payment_type', IntEnum(PaymentType), nullable=False),
    sa.Column('services', sa.ARRAY(IntEnum(ServiceType)), nullable=False),
    sa.Column('departure_location_id', sa.Integer(), nullable=True),
    sa.Column('arrival_location_id', sa.Integer(), nullable=True),
    sa.Column('address_1_id', sa.Integer(), nullable=True),
    sa.Column('address_2_id', sa.Integer(), nullable=True),
    sa.Column('address_3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_1_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['address_2_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['address_3_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['arrival_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['departure_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('caption_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    op.drop_table('location')
    # ### end Alembic commands ###
