"""empty message

Revision ID: c417279873a5
Revises: 02803c68951a
Create Date: 2022-05-23 11:16:43.681289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c417279873a5'
down_revision = '02803c68951a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('address_1_id', sa.Integer(), nullable=False))
    op.add_column('trip', sa.Column('address_2_id', sa.Integer(), nullable=False))
    op.add_column('trip', sa.Column('address_3_id', sa.Integer(), nullable=False))
    op.alter_column('trip', 'contact_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'trip', 'location', ['address_2_id'], ['id'])
    op.create_foreign_key(None, 'trip', 'location', ['address_1_id'], ['id'])
    op.create_foreign_key(None, 'trip', 'location', ['address_3_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.alter_column('trip', 'contact_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('trip', 'address_3_id')
    op.drop_column('trip', 'address_2_id')
    op.drop_column('trip', 'address_1_id')
    # ### end Alembic commands ###
